### ISSUE TITLE
Cannot compile on Arch Linux

### ISSUE THREAD

**Issue by aspizu** [LordOfTrident/pona#1]
```
/usr/bin/ld: cannot find -lncursesw: No such file or directory
/usr/bin/ld: cannot find -ltinfo: No such file or directory
```

**Comment by LordOfTrident** [comment]
seems like you dont have the static ncursesw library, not sure what exactly it comes with if you already have ncursesw. Im gonna update the makefile to add a `shared` option, you can try that: `make shared`

**Comment by aspizu** [comment]
works!
